# Generated by Django 2.2.5 on 2020-03-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lname',
        ),
    ]
