# Generated by Django 2.2.5 on 2020-03-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200316_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='f_name',
        ),
    ]
